version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1.25
    container_name: fuzzy-potato-app
    restart: unless-stopped
    volumes:
      - ../:/workspaces/${localWorkspaceFolderName}:cached
    command: sleep infinity
    ports:
      - "9000:9000"
    networks:
      - dev-network

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data:
  redis-insight-data:
